[package]
name = "curse_screen"
version = "0.1.0"
authors = ["SQUARE-WAVES <michael.behrman@gmail.com>"]
edition = "2018"

[dependencies]
termion="1.5.3"
midir = "0.5.0"
adi_clock = "0.1.1"
serde = {version="1.0.101", features=["derive"]}
serde_json = "1.0.41"